x= 10
y= 10.01
z= "oh i see"
i= "@"
j= False 
k= None
print ("the type of x = \"",x,"\" is" ,type(x))
print ("the type of y = \"",y,"\" is" ,type(y))
print ("the type of z = \"",z,"\" is" ,type(z))
print ("the type of i = \"",i,"\" is" ,type(i))
print ("the type of j = \"",j,"\" is" ,type(j))
print ("the type of k = \"",k,"\" is" ,type(k))